name: Test app with Maven

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
        - 3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
    - name: Verify MySQL connection from host
      run: |
         mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Cache Maven packages
#      uses: actions/cache@v1
#      with:
#        path: ~/.m2
#        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#        restore-keys: ${{ runner.os }}-m2

#    - name: Build with maven
#      run: mvn test -DMYSQL_PASSWORD=password
